### ISSUE TITLE
Problem with fewer length

### ISSUE THREAD

**Issue by paulocoutinhox** [0rangeFox/Drogon-JWT-Filter-example#2]
Hi,

In this line:
https://github.com/0rangeFox/Drogon-JWT-Filter-example/blob/0ac8a197171637ddbd1af70bb57f61f252df6621/src/filters/JwtFilter.cc#L25

Will happen a crash if the header has `length < 7`.

Thanks.

**Comment by 0rangeFox** [comment]
Hey @paulocoutinhox 👋, I'm really sorry for long delay and I don't know why I don't receive this important notifications... Anyways, later I will PR about the fix for this crash. Thanks.

**Comment by 0rangeFox** [comment]
Here is the solution to the problem. Thanks again for letting me know about this error. Anything else I can help you with, just let me know. Happy programming!
